default_platform(:ios)

platform :ios do
  desc "Upload to App Store Connect via TestFlight / App Store"
  lane :deploy do
    api_key = app_store_connect_api_key(
      key_id: "L2XRGXQYP6",
      issuer_id: "375bd958-10b5-4bcd-b556-44925a5192a9",
      key_filepath: "~/.config/appstore/AuthKey_L2XRGXQYP6.p8"
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: "../build/ios/ipa/Joey.ipa",
      skip_metadata: false,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      submit_for_review: true,
      automatic_release: true,
      submission_information: { export_compliance_uses_encryption: false },
      force: true
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "L2XRGXQYP6",
      issuer_id: "375bd958-10b5-4bcd-b556-44925a5192a9",
      key_filepath: "~/.config/appstore/AuthKey_L2XRGXQYP6.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/Joey.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
