default_platform(:android)

platform :android do
  desc "Deploy to Google Play production track"
  lane :deploy do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
